title: GeckoView
email: etoop@mozilla.com
description:
  The privacy focussed WebView you've been looking for.
baseurl: "" # the subpath of your site, e.g. /blog
url: "mozilla.github.io/geckoview" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: geckoview
github_username:  mozilla

# Build settings
markdown: kramdown
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed
  - jekyll-seo-tag

search_enabled: true

